CREATE DATABASE Flippelis
GO

USE Flippelis
GO

CREATE TABLE USERACCOUNT(
Email NVARCHAR(40) NOT NULL CONSTRAINT UK_USRACCOUNT_UsrEmail UNIQUE,
ProfilePic IMAGE NULL,
UserType CHAR(1) NULL DEFAULT 'I' CONSTRAINT CH_USERACCOUNT_Type CHECK(UserType IN('A', 'I', 'U')),
UserName NVARCHAR(20) NOT NULL CONSTRAINT PK_USERACCOUNT_UserName PRIMARY KEY,
Pswd  NVARCHAR(24) NOT NULL)
GO

CREATE TABLE LVIEWED(
UserName NVARCHAR(20) NOT NULL,
ProdID NUMERIC(13,0) NOT NULL,
CONSTRAINT PK_LVIEWED_UsrNameProdID PRIMARY KEY(UserName,ProdID))
GO

CREATE TABLE LFAVS(
UserName NVARCHAR(20) NOT NULL,
ProdID NUMERIC(13,0) NOT NULL,
CONSTRAINT PK_LFAVS_UsrNameProdID PRIMARY KEY(UserName,ProdID))
GO

CREATE TABLE WISHLIST(
UserName NVARCHAR(20) NOT NULL,
ProdID NUMERIC(13,0) NOT NULL,
CONSTRAINT PK_WISHLIST_UsrNameProdID PRIMARY KEY(UserName,ProdID))
GO

CREATE TABLE PRODUCT(
ProdID NUMERIC(13,0) NOT NULL CONSTRAINT PK_PRODUCT_ID PRIMARY KEY
CONSTRAINT CH_PRODUCT_ID CHECK(ProdID LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'),
Title NVARCHAR(40) NOT NULL CONSTRAINT UK_PRODUCT_Title UNIQUE,
Rate NUMERIC(3,0) NULL DEFAULT 0,
ReleaseDate DATE NULL,
Characters NVARCHAR(200) NULL,
Synopsis NVARCHAR(500) NULL,
Genre VARCHAR(10) NOT NULL,
Prizes NVARCHAR(100) NULL,
Collect MONEY NULL,
Trailer VARCHAR(50) NULL,
Images IMAGE NOT NULL,
FDub VARCHAR(300) NULL,
Platf VARCHAR(50) NULL,
Compositor NVARCHAR(40) NULL,
BSO VARCHAR(100) NULL,
Director NVARCHAR(40) NOT NULL,
Producer NVARCHAR(30) NULL)
GO

CREATE TABLE REVIEWS(
UserName NVARCHAR(20) NOT NULL,
ProdID NUMERIC(13,0) NOT NULL,
Comment VARCHAR(500) NULL,
Rate NUMERIC(3,0) NOT NULL,
ReviewRate SMALLINT NULL DEFAULT 0,
CONSTRAINT PK_HISTORY_UsrNameProdID PRIMARY KEY(UserName,ProdID))
GO

CREATE TABLE SERIES(
ProdID NUMERIC(13,0) NOT NULL CONSTRAINT PK_SERIES_ProdID PRIMARY KEY,
TotalEpisodes TINYINT NOT NULL,
TotalSeasons TINYINT NOT NULL,
EpDuration TINYINT NULL,)
GO

CREATE TABLE MOVIES(
ProdID NUMERIC(13,0) NOT NULL CONSTRAINT PK_MOVIES_ProdID PRIMARY KEY,
Franchise VARCHAR(50) NULL,
Duration TINYINT NOT NULL,)

GO

ALTER TABLE LVIEWED ADD CONSTRAINT FK_HISTORY_UsrName FOREIGN KEY(UserName) REFERENCES USERACCOUNT(UserName)
ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE LVIEWED ADD CONSTRAINT FK_HISTORY_ProdID FOREIGN KEY(ProdID) REFERENCES PRODUCT(ProdID)
ON DELETE NO ACTION ON UPDATE CASCADE
GO
ALTER TABLE LFAVS ADD CONSTRAINT FK_LFAVS_UsrName FOREIGN KEY(UserName) REFERENCES USERACCOUNT(UserName)
ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE LFAVS ADD CONSTRAINT FK_LFAVS_ProdID FOREIGN KEY(ProdID) REFERENCES PRODUCT(ProdID)
ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE WISHLIST ADD CONSTRAINT FK_WISHLIST_UsrName FOREIGN KEY(UserName) REFERENCES USERACCOUNT(UserName)
ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE WISHLIST ADD CONSTRAINT FK_WISHLIST_ProdID FOREIGN KEY(ProdID) REFERENCES PRODUCT(ProdID)
ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE SERIES ADD CONSTRAINT FK_SERIES_ProdID FOREIGN KEY(ProdID) REFERENCES PRODUCT(ProdID)
ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE MOVIES ADD CONSTRAINT FK_MOVIES_ProdID FOREIGN KEY(ProdID) REFERENCES PRODUCT(ProdID)
ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE REVIEWS ADD CONSTRAINT FK_REVIEWS_UsrName FOREIGN KEY(UserName) REFERENCES USERACCOUNT(UserName)
ON DELETE NO ACTION ON UPDATE CASCADE
GO
ALTER TABLE REVIEWS ADD CONSTRAINT FK_REVIEWS_ProdID FOREIGN KEY(ProdID) REFERENCES PRODUCT(ProdID)
ON DELETE NO ACTION ON UPDATE CASCADE
GO
